# Generated by Django 4.2.2 on 2023-06-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(blank=True, max_length=10)),
                ('released', models.CharField(blank=True, max_length=20)),
                ('runtime', models.CharField(blank=True, max_length=10)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('writer', models.CharField(blank=True, max_length=200)),
                ('actors', models.CharField(blank=True, max_length=500)),
                ('plot', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('awards', models.TextField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('ratings', models.TextField(blank=True)),
                ('metascore', models.CharField(blank=True, max_length=10)),
                ('imdbRating', models.CharField(blank=True, max_length=4)),
                ('imdbVotes', models.CharField(blank=True, max_length=10)),
                ('imdbID', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('dvd', models.CharField(blank=True, max_length=20)),
                ('boxOffice', models.CharField(blank=True, max_length=20)),
                ('production', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('response', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
